source "https://rubygems.org"

gem "jekyll", "~> 4.4.0"
gem "kramdown", "~> 2.4.0"
gem "kramdown-parser-gfm", "~> 1.1"
gem "rouge", "~> 4.0"
gem "jekyll-sass-converter", "~> 3.0"
gem "jekyll-paginate-v2", "~> 3.0"
gem "json", "~> 2.7"
gem "webrick", "~> 1.8"
gem "logger", "~> 1.6"
